# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://new.cbelena.es/"
defaultContentLanguage = "es"
timeZone = "Europe/Madrid"
publishDir = "../html"
buildDrafts = true
theme = "congo"
enableRobotsTXT = true
pluralizeListTitles = false
disableKinds = ["taxonomy", "term", "404"]
rssLimit = 25

[outputs]
  home = ["HTML"]

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
